### ISSUE TITLE
Manifest.xml

### ISSUE THREAD

**Issue by baixjian** [LLeavesG/Android-DirtyStream#1]
Thanks for sharing, I wonder if the absence of FileActivity in Manifest.xml prevents this vulnerability

**Comment by baixjian** [comment]
I have a React Native project that relies on `rn-fetch-blob` [AndroidManifest.xml](https://github.com/joltup/rn-fetch-blob/blob/v0.12.0/android/src/main/AndroidManifest.xml#L26)
`react-native-image-crop-picker ` [AndroidManifest](https://github.com/ivpusic/react-native-image-crop-picker/blob/v0.35.1/android/src/main/AndroidManifest.xml#L14)
Whether these dependencies can also lead to vulnerabilities

**Comment by LLeavesG** [comment]
In fact, this can be avoided as long as the FileActivity is non-exported, but there are actually scenarios where the FileActivity must be registered in Manifest.xml and exported in order to provide shareTarget functionality. The easiest way to defend against this vulnerability is to carefully check that the incoming data is properly santizerized.、

Regarding the two projects you mentioned, I note that they contain registrations for FileProvider and are both non-exported, and are generally not vulnerable to this vulnerability unless the attacker achieves FileProvider abuse by passing malicious data to other exported components (e.g., reading a file via DirtyStream or achieving authorization of the Provider via Intent Redirect Vuln to achieve Provider authorization, etc.). So as I mentioned above, other exported components are the entry point and the key, and santizing the data passed to the exported components will avoid attacks.

**Comment by baixjian** [comment]
> In fact, this can be avoided as long as the FileActivity is non-exported, but there are actually scenarios where the FileActivity must be registered in Manifest.xml and exported in order to provide shareTarget functionality. The easiest way to defend against this vulnerability is to carefully check that the incoming data is properly santizerized.、
> 
> Regarding the two projects you mentioned, I note that they contain registrations for FileProvider and are both non-exported, and are generally not vulnerable to this vulnerability unless the attacker achieves FileProvider abuse by passing malicious data to other exported components (e.g., reading a file via DirtyStream or achieving authorization of the Provider via Intent Redirect Vuln to achieve Provider authorization, etc.). So as I mentioned above, other exported components are the entry point and the key, and santizing the data passed to the exported components will avoid attacks.

Thank you for your reply. I understand. Thanks again
